module.exports = {
  STATUS_CODES: {
    STATUS_CODE_200: 200,
    STATUS_CODE_201: 201,
  },
  ERRROR_STATUS_CODES: {
    STATUS_CODE_400: 400,
  },
  STATUS_MESSAGES: {
    STATUS_MESSAGE_SUCCESS: "Success",
  },
};
